language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - cd ./DataLineageApp
  - npm install
  - npm run clean:js
script:
  - npm run build:prod
before_deploy:
  - cp web.config ./dist
  - cp package.json ./dist
  - cd ./dist
git:
   depth: 9999999
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  username: admchenbo
  password: $AZURE_WA_PASSWORD
  site: datalineage-viewer